version: "3"

services:
  demo:
    container_name: spring-demo
    image: rootknecht.net/spring-demo:latest
    environment:
      - stage=dev
      - DATABASE_USER=db
      - DATABASE_PASSWORD=db
      - DATABASE_NAME=db
      - DATABASE_HOST=db
      - DATABASE_PORT=1234
    env_file:
      - ./conf/data.env
    ports:
      - 8080:8080