version: "3.1"

services:
  spring-demo:
    container_name: spring-demo
    image: rootknecht.net/spring-demo:latest
    environment:
      - stage=dev
      - DATABASE_USER=db
      - DATABASE_PASSWORD=db
      - DATABASE_NAME=db
      - DATABASE_HOST=db
      - DATABASE_PORT=1234
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINTS_JMX_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_METRICS_ENABLED=true
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true
    env_file:
      - ./conf/data.env
    restart: always
    networks:
      - back-tier
    ports:
      - 8080:8080