logging:
  level:
    .: error
    org.springframework: ERROR
    com.mkyong: ERROR

spring:
  profiles:
    # wil be set by docker-compose file
    # active: "dev"
    # include: "prod"
  main:
    banner-mode: "off"

server:
  email: default@rootknecht.net

---

spring:
  profiles: dev
datasource:
  url: jdbc:mysql://localhost:3306/demo
  username: root
  password: p4SSW0rd
  platform: mysql
  initialize: false
jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
server:
  email: dev@rootknecht.net
  cluster:
    - ip: 127.0.0.1
      path: /dev1
    - ip: 127.0.0.2
      path: /dev2
    - ip: 127.0.0.3
      path: /dev3

---

spring:
  profiles: prod
datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true
server:
  email: prod@rootknecht.net
  cluster:
    - ip: 192.168.0.1
      path: /app1
    - ip: 192.168.0.2
      path: /app2
    - ip: 192.168.0.3
      path: /app3
