# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'spring-boot-demo'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'spring-boot'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-demo:8080']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
         - targets: ['cadvisor:8080']

  - job_name: 'node'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
         - targets: ['node-exporter:9100']